name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.3.1
  - plyfile=0.8.1
  - tqdm
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pip:
      - ninja
      - cmake
